lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl:  31536000 # Expiration delay in seconds
    #    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    #    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    #    pass_phrase:      'zogzog' # required for token creation, usage of an environment variable is recommended